Redunce dependency list to be package link and arrow for walking up or down
ros-infrastructure/rosindex pull request #423
Opened 2024-09-15 08:04 UTC by tfoote

This fixes #388 

It fixes the broken links by removing them as the extra column's info has been reduced. And while here make it symmetric so you navigate packages both up and down the dependency list.

2024-09-16 08:03 UTC, rkent requested changes
Overall I like this, the symmetry is nice. Also, in many cases the arrows under "Dependant Packages" did not show at all, blocked by the repo id. Now they do.

Some small suggested changes:

1) The section that you changed is under `{% if n_dependants > 0 %}`  You also need to delete the `<td>` in the else clause:
```
-                        <td class="text-center">
-                          <span class="label label-danger">0</span>
-                        </td>
```
2) With the removal of the repo link, the right hand side no longer needs a lot of space, but the columns are divided `<div class="col-sm-5">` and `<div class="col-sm-7">`. Make both of these `<div class="col-sm-6">` which will reinforce the symmetry.

One additional optional note. I don't really like the graying of the arrows (`class=inactive`) when a target has zero dependencies, graying usually means disabled so it is confusing to me here to use it differently. But it pre-exists, so I'd like to see it at least consistent. The left arrows track both system dependencies as well as packages, while the right only packages (that is, there are no system dependencies that depend on ROS packages). Previously it was rare to actually see the gray right arrows because of the above-mentioned blocking, now they are everywhere. If we are going to leave this, I would change it to match only ROS package dependencies so that both sides are consistent, to mean "This is the bottom (or top) of a tree of ROS dependencies". I don't really care about system dependencies for that. So I would change:
```
{% assign n_2nd_order_pdeps = p[1].snapshots[distro].data.pkg_deps | size %}
{% assign n_2nd_order_sdeps = p[1].snapshots[distro].data.system_deps | size %}
{% assign n_2nd_order_deps = n_2nd_order_pdeps | plus: n_2nd_order_sdeps %}
```
to:
```
{% assign n_2nd_order_deps = p[1].snapshots[distro].data.pkg_deps | size %}
```

2024-09-16 20:22 UTC, rkent commented
BTW I implemented my suggested changes [here](https://github.com/rkent/rosindex/commit/647a21b93154616dd827313e814bf638fa668345) and they are merged into my development build at index.rosdabbler.com. I switched the gray to purple so it does not look like disabled on the arrows.

2024-09-25 00:35 UTC, tfoote commented
Thanks for the feedback. If you'd like to break out your changes and replace this PR with the more complete changes you proposoed I'd be happy to do that instead.

2024-09-25 03:55 UTC, rkent commented
"If you'd like to break out your changes and replace this PR with the more complete changes you proposed I'd be happy to do that instead."

I've pretty much already done that, and it is running in https://devindex.rosdabbler.com  See https://github.com/rkent/rosindex/tree/tfoote-rkent-simplify-dependency-table  I added one commit on top of your PR. I'll PR it, then you can decide what to do with it.

2024-09-25 20:40 UTC, tfoote commented
Replaced by #427

2024-09-25 20:40 UTC, closed without merging